### ISSUE TITLE
Meta-issue

### ISSUE THREAD

**Issue by Sydpy** [Sydpy/clusterify#1]
**Improvements**
- [ ] Write a README
- [ ] Possibility to run on the user library
- [ ] `--feature-types` option could also accept lowercase/uppercase feature type names

**To discuss**
- [ ] Change default features ? Are `Acousticness` and `Liveness` something that are relevant as default features ?
- [ ] Support more features ? Currently only features mapped inside [0;1] are supported, a strategy for mapping features with values inside a bigger space might be necessary
